apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-frontend
  template:
    metadata:
      labels:
        app: auth-frontend
    spec:
      imagePullSecrets:
      - name: registry-credentials
      containers:
        - name: auth-frontend
          image: stokei/auth-frontend:latest
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          imagePullPolicy: Always
          env:
            - name: NEXT_PUBLIC_AUTH_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: urls-configmap
                  key: auth-gateway-url
            - name: NEXT_PUBLIC_PAINEL_URL
              valueFrom:
                configMapKeyRef:
                  name: urls-configmap
                  key: apps-painel-frontend-url
            - name: NEXT_PUBLIC_PAINEL_ADMIN_URL
              valueFrom:
                configMapKeyRef:
                  name: urls-configmap
                  key: apps-painel-admin-frontend-url