apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - auth.stokei.com
      secretName: auth-frontend-tls
  rules:
    - host: auth.stokei.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: auth-frontend-service
                port:
                  number: 80